### ISSUE TITLE
Documentation - App Web Src - Customize Build

### ISSUE THREAD

**Issue by klcodanr** [adobe/aio-cli-plugin-app#124]
**Is your feature request related to a problem? Please describe.**
If I wanted to customize the build stage / content of the webapp, is that possible? Imagine I wanted to use a LESS / SASS precompiler or TypeScript, how would I do that?

**Describe the solution you'd like**
Documentation :-)

**Describe alternatives you've considered**
I've seen that you can reference code from Node Modules and there's definitely some magic going on, but I am not a fan of cargo cult programming so I was hoping to have some documentation to understand what is happening and how as a developer I can extend it.

**Additional context**

**Comment by meryllblanchet** [comment]
Hi @klcodanr and thanks for reaching out.
This is not possible yet and we'll be very opinionated in the technical support we provide for the development lifecycle of the first applications. 

We have in mind that more flexibility will be required especially on the front-end side in order to surface a larger panel of use-cases, to be addressed by our team in the longer run.

As a short-term solution, you could build your own [plugin](https://oclif.io/docs/plugins) for the CLI. The drawback would be on the implementation effort, and deviation from our reference app plugin.

**Comment by klcodanr** [comment]
@meryllblanchet Makes sense, at some point will there be more docs on what you _can_ do with the current setup?

**Comment by meryllblanchet** [comment]
@klcodanr We have a very first documentation within the [CLI](https://github.com/adobe/aio-cli) repository itself. We're working to provide a more detailed documentation soon.

**Comment by meryllblanchet** [comment]
Closing the issue as we are generally writing the developer documentation on https://github.com/AdobeDocs/adobe-custom-applications.
