### ISSUE TITLE
Cannot See Characters Entered After aio app run

### ISSUE THREAD

**Issue by klcodanr** [adobe/aio-cli-plugin-app#127]
### Expected Behaviour
After I exit `aio app run` I can enter other commands and see the output.

### Actual Behaviour
If I exit `aio app run` with ctri+c, I can no longer see any text I enter into the command prompt. The only way to get back to a good state is to execute the `reset` command.

#### Steps to Reproduce

- Run the command: `aio app run`
- Press ctrl + c to exit
- Enter anything into the terminal

#### Platform and Version

 - OS: MacOS Mojave 10.14.6
 - Bash 3.2
 - Node v13.5.0
 - @adobe/aio-cli/2.2.3

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by purplecabbage** [comment]
Node v13.5.0 is experimental, can you try again with an LTS version, 12.x just to be sure?

**Comment by OmarEltobgy** [comment]
I have the same problem and I am using Node x12.13.0

**Comment by purplecabbage** [comment]
so fast ...

**Comment by purplecabbage** [comment]
I have not been able to reproduce this issue.  Does this still occur in more recent versions of the aio-cli and aio-cli-plugin-app?
@adobe/aio-cli/ is now @3.0.0
and aio-cli-plugin-app@1.3.0 was published this morning.

If you are still able to reproduce this issue in the latest versions, please run your command with verbose output: 
`DEBUG=@adobe/aio-app-scripts*,aio-cli-plugin-app* aio app run`

**Comment by purplecabbage** [comment]
assuming this is resolved, please re-open if you still experience this issue.

**Comment by moritzraho** [comment]
Update:

1. Could reproduce with:
- node 12
- no external monitor
- bash v3
- iterm2
- osx (mojave)

2. Bug doesn't apply if (one of those condition is sufficient):
- node 10 (instead of node 12)
- with external monitor (instead of mac screen)
- zsh (instead of bash)
- default mac terminal (instead of iterm 2)

This is probably related to parcelv1's dev server that we use internally in aio run:
- `parcel-bundler@1.12` + all bug conditions: `parcel dist/web-src-dev/index.html` + CTRL-C
=> same bug
- `parcel@2.0.0-alpha.3.2` + all bug conditions: `parcel dist/web-src-dev/index.html` + CTRL-C
=> no bug

**Comment by moritzraho** [comment]
fixed
