### ISSUE TITLE
What's with the Crazy Project Names?

### ISSUE THREAD

**Issue by klcodanr** [adobe/aio-cli-plugin-app#238]
**Describe the bug**
It looks like the AIO Console is assigning a Docker-style autogenerated name to all of the projects, even though you may have given the project a title which then gets used in Project Firefly as the package name. It would make more sense to use either the folder name or the Project Title (110% folder name IMO) as the title instead of the autogenerated project names.

**To Reproduce**
1. Create a new project with `aio app init`
2. Look at the package.json and note the name

**Expected behavior**
The name is based on the folder name in which the app is initialized or requested from the user at init time. 

**Screenshots**

![image](https://user-images.githubusercontent.com/2946250/82328992-a16f3300-99ae-11ea-8ef8-f93349e5734f.png)

**Desktop (please complete the following information):**
@adobe/aio-cli/3.4.1 darwin-x64 node-v14.2.0

**Additional context**

**Comment by meryllblanchet** [comment]
Hi @klcodanr ,

Thanks for reaching out! Please have a look at our [Getting Started](https://github.com/AdobeDocs/project-firefly/blob/master/getting_started/first_app.md) page.

The application name is imported from the corresponding Developer Console Project when bootstrapping the application from the CLI.

As documented in the section 2.5, you can edit the application name in the Developer Console when creating the project, but you won't be able to change it later.

cc @sarahxxu

**Comment by klcodanr** [comment]
Thanks @meryllblanchet that makes sense, I'm assuming it's just because I was using a "legacy" project.

**Comment by meryllblanchet** [comment]
Most likely @klcodanr, you might want to try with a new fresh project created from the `Project Firefly template` in the Developer Console. 
Don't hesitate to reach out in case you'd have other questions.

**Comment by klcodanr** [comment]
Re-opening, I'm not seeing the ability to actually set a project name when creating a new project: 

![New-Project](https://user-images.githubusercontent.com/2946250/82330894-66223380-99b1-11ea-93b2-8766e557cb0c.gif)

**Comment by duynguyen** [comment]
@klcodanr , can you try creating new project from https://console.adobe.io/projects ? You will see Firefly template as an option.

**Comment by klcodanr** [comment]
Same result:
![New-Project-Screen2](https://user-images.githubusercontent.com/2946250/82332322-3c6a0c00-99b3-11ea-9f07-6b9c13ec0284.gif)

Which actually brings me to another question, how do I delete these projects I've created?

**Comment by meryllblanchet** [comment]
@klcodanr we'll check that your org is setup properly in order to be able to create a new project based on the "Project Firefly" template. The option is missing for your org from what I see from your UI and admin role. See 
the [Console Project Template documentation](https://www.adobe.io/apis/experienceplatform/console/docs.html#!AdobeDocs/adobeio-console/master/projects-template.md).

You cannot delete the projects for now.

**Comment by sarahxxu** [comment]
Hi Dan,  you don’t see the option to create project from Firefly template because your org is not yet added to Developer Preview. I'll follow up with you to ensure your org is enabled. 

At the meantime -- yes Meryll is correct in that once an org is created, the "app name" for your project, once generated, can not be modified because they are unique identifiers. the project name, the one you see in Console, is modifiable. 

The app name is a new property. If you are using an older project, I believe a randomly generated name was assigned to all existing projects -- hence showing the name listed in your manifest.
