### ISSUE TITLE
Unable to view Published app in experience cloud 

### ISSUE THREAD

**Issue by igirish-kumar** [adobe/aio-cli-plugin-app#534]
**Describe the bug**
We have created an app using “DX Experience Shell” , It is approved and published, status in console states its Published, But we are unable to view under Experience cloud -> App builder Catlog

**To Reproduce**
The build and deployment log as been attached 

**Expected behavior**
Able to see published app under experience cloud -> App catalog
**Screenshots**
<img width="959" alt="deploy" src="https://user-images.githubusercontent.com/78724249/168056420-96ad93e6-a382-4382-bae1-804e1b835b6e.png">
<img width="547" alt="Screenshot 2022-05-12 at 2 26 03 PM" src="https://user-images.githubusercontent.com/78724249/168056459-4ad5be16-4a80-4b4c-a97d-b2229443b1a6.png">
<img width="1013" alt="BUILD LOG1" src="https://user-images.githubusercontent.com/78724249/168056507-203a9626-6752-40a2-999f-ca9f7e2154ff.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by purplecabbage** [comment]
Try using the proper commands please.
You are running `aio app:project:select` instead of `aio console:project:select` and `aio app:workspace:select` instead of `aio project:workspace:select` ... all of these are causing exceptions internally, and even though you are 'auto-suggested' the correct command, it is hard to know if this is causing the issue.

The recommended way to bind a code-repo to a dev-console project is to go to the project/workspace page, and select **Download All** 
This will give you a json file with all the config for the project/workspace, then you simply run 
`aio app use <downloaded-file.json>`

**Comment by NickRumenov** [comment]
Hi @purplecabbage , i have the same issue, pushed an application but it doesn't appear in App Builder Catalog.
Please do share what are the steps int and deploy a project once we download the JSON file from the Project

**Comment by igirish-kumar** [comment]
Hi @purplecabbage I am unable to Download JSON since the app published in production workspace is Read Only, though I do have admin access.

**Comment by NickRumenov** [comment]
@igirish-kumar i had the same issue and couldn't download the json but i executed this command in the terminal 
`aio app use -w Production`
It changed both .aio and .env files with the production configurations which I consider as same as what we need

After that I ran 
`aio app deploy`
but it also didn't deploy the application in app-builder catalog, it ran successfully and deployed the in the long URL with the devmode=true and localhost=...
![Screenshot 2022-06-07 at 11 48 15](https://user-images.githubusercontent.com/13507987/172338184-ac1a8945-946b-4770-a71f-4b7a99eb54b5.png)
But I noticed this row in the terminal `skipping publish phase...`
What does that mean?
@purplecabbage please advise what we should do in order to publish the app since all configurations look correct and production workspace is selected. How can we list the app in the catalog?
Thanks

**Comment by NickRumenov** [comment]
btw, i also received an email that the app is successfully approved and published
`our application is now available in Experience Cloud. If you have any questions, please refer to the [App Builder documentation](https://www.adobe.io/apis/experienceplatform/project-firefly/docs.html).`
All good but the app still doesn't appear

**Comment by MichaelGoberling** [comment]
@igirish-kumar Even though the CLI has been configured to use the Production workspace of your application, the project you are working on may still be configured to use the Stage workspace locally. I would suggest running `aio app use` in your project's directory and inspecting the `.env` file in the project directory to ensure production values are present before trying again.

@NickRumenov Was the application you created initialized as `Standalone Application` or as `DX Experience Cloud SPA v1`? It must be initialized as the latter in order to show up in the App Builder Catalog. You can verify this by looking at the app in Exchange. If the app has the `App Builder ExcShell` subheading (see below), then it should show up in App Builder Catalog after approval. If it does not, then you may need to go through some migration steps, which I will document and link here once they're complete. 

![image](https://user-images.githubusercontent.com/28722775/173150016-ba3c09ec-b053-43c0-9f7a-52352dd4f9d4.png)

**Comment by igirish-kumar** [comment]
@purplecabbage , The issue still exists even after using production workspace and we could see some errors on executing  aio app deploy as below :

✔ Built 4 action(s) for 'dx/excshell/1'
✔ Building web assets for 'dx/excshell/1'
✔ Deployed 8 action(s) for 'dx/excshell/1'
✔ Deploying web assets for 'dx/excshell/1'
Your deployed actions:
web actions:
  -> https://25605-mvplabservicecenter.adobeio-static.net/api/v1/web/dx-excshell-1/generic
  -> https://25605-mvplabservicecenter.adobeio-static.net/api/v1/web/dx-excshell-1/getProfile
  -> https://25605-mvplabservicecenter.adobeio-static.net/api/v1/web/dx-excshell-1/getExperienceEvents
  -> https://25605-mvplabservicecenter.adobeio-static.net/api/v1/web/dx-excshell-1/postEvent
non-web actions:
  -> dx-excshell-1/__secured_generic
  -> dx-excshell-1/__secured_getProfile
  -> dx-excshell-1/__secured_getExperienceEvents
  -> dx-excshell-1/__secured_postEvent
To view your deployed application:
  -> https://25605-mvplabservicecenter.adobeio-static.net/index.html
To view your deployed application in the Experience Cloud shell:
  -> https://experience.adobe.com/?devMode=true#/custom-apps/?localDevUrl=https://25605-mvplabservicecenter.adobeio-static.net/index.html
⠋ Updating Extension Points 'endpoints' in Workspace=Production... ›   Error: [CoreConsoleAPISDK:ERROR_UPDATE_WORKSPACE_ENDPOINTS] 400 - Bad Request
 ›   ([{"template":"ERR_MSG_RETRY_OR_CONTACT","message":"{\"errors\":[{\"error_code\":\"1400\",\"message\":\"Problem occured - App in
 ›   DRAFT|REJECTED|RETRACTED status can only be updated\"}]}"}])
⠙ Updating Extension Points 'endpoints' in Workspace=Production...

**Comment by MichaelGoberling** [comment]
@igirish-kumar It seems like you are trying to update extension point configuration for an application that is already published. Try revoking the application, giving the deploy another try, and then re-publishing the application.

**Comment by igirish-kumar** [comment]
@MichaelGoberling , That worked, Thanks for all your support.

**Comment by MichaelGoberling** [comment]
@igirish-kumar Glad to help.

@NickRumenov Following up, have you been able to view your application in Experience Cloud?

**Comment by purplecabbage** [comment]
Closing this as resolved.  If you still have issues @NickRumenov please open a new issue.

**Comment by NickRumenov** [comment]
Ok i will test it, thanks for the support
